# Generated by Django 5.1.6 on 2025-05-15 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unseen_friend_requests',
            field=models.ManyToManyField(blank=True, related_name='unseen_requests_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
