# Generated by Django 5.1.6 on 2025-05-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vite', '0002_customuser_unseen_friend_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='unseen_friend_requests',
        ),
    ]
