# Generated by Django 5.1.6 on 2025-05-21 13:25

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vite', '0005_message_image_message_video_alter_message_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.RemoveField(
            model_name='message',
            name='video',
        ),
        migrations.AddField(
            model_name='customuser',
            name='cover_photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='cover_photos/default_cover.jpg', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
