# Generated by Django 5.1.6 on 2025-05-30 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vite', '0010_story'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
