# Generated by Django 5.1.6 on 2025-06-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vite', '0013_reel_reelcomment_reellike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'رسالة جديدة'), ('like', 'إعجاب'), ('comment', 'تعليق'), ('friend_request', 'طلب صداقة'), ('friend_accept', 'قبول الصداقة'), ('reel_like', 'إعجاب على ريل'), ('reel_comment', 'تعليق على ريل')], max_length=20),
        ),
    ]
