# Generated by Django 5.1.6 on 2025-06-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vite', '0015_customuser_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
