# Generated by Django 5.1.6 on 2025-06-10 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vite', '0018_conversation_aimessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
        migrations.DeleteModel(
            name='AIMessage',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
