# Generated by Django 5.1.6 on 2025-06-10 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vite', '0019_remove_conversation_user_delete_aimessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewed_reels', to=settings.AUTH_USER_MODEL),
        ),
    ]
