# Generated by Django 5.1.6 on 2025-06-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vite', '0020_reel_viewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_system_message',
            field=models.BooleanField(default=False),
        ),
    ]
