# Generated by Django 5.1.6 on 2025-06-12 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vite', '0022_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'رسالة جديدة'), ('like', 'إعجاب'), ('comment', 'تعليق'), ('friend_request', 'طلب صداقة'), ('friend_accept', 'قبول الصداقة'), ('reel_like', 'إعجاب على ريل'), ('reel_comment', 'تعليق على ريل'), ('story_like', 'إعجاب على القصة')], max_length=20),
        ),
        migrations.CreateModel(
            name='StoryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_likes', to='vite.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'story')},
            },
        ),
    ]
