# Generated by Django 5.1.6 on 2025-08-05 04:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vite', '0023_alter_notification_notification_type_storylike'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='voice_note',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
