# Generated by Django 5.1.6 on 2025-08-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vite', '0026_post_voice_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blue_badge',
            field=models.BooleanField(default=False),
        ),
    ]
