# Generated by Django 5.1.6 on 2025-08-11 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vite', '0027_customuser_blue_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='blue_badge',
        ),
    ]
